3.1 텐서와 그래프 실행

In [45]:
import numpy as np
import tensorflow as tf

In [46]:
hello = tf.constant('Hello tf?')
print(hello)

Tensor("Const_32:0", shape=(), dtype=string)


In [47]:
a = tf.constant(10)
b = tf.constant(22)
b2 = tf.constant(20)
c = tf.add(a,b)
c2 = tf.add(c,b2)
print(a,'\n',b,'\n',c)

Tensor("Const_33:0", shape=(), dtype=int32) 
 Tensor("Const_34:0", shape=(), dtype=int32) 
 Tensor("Add_15:0", shape=(), dtype=int32)


In [48]:
sess = tf.Session()
d = sess.run(hello)
print(d)

b'Hello tf?'


In [49]:
print(sess.run([c2,c]))
sess.close()

[52, 32]


3.2 플레이스 홀더와 변수

In [54]:
X = tf.placeholder(tf.float32, [None, 3])
print(X)

Tensor("Placeholder_3:0", shape=(?, 3), dtype=float32)


In [97]:
x_data = [[1,2,3],[4,5,6]]

# W = tf.Variable(tf.random_normal([3,2])) #[3,2] 행렬형태에 정규분포 값을 넣어준다.
# b = tf.Variable(tf.random_normal([2,1]))

W = tf.Variable([[1.,1.],[2.,3.],[1.,5.]])
b = tf.Variable([[3.],[7.]])

In [98]:
#행렬 변수를 계산 tf.matmul
expr = tf.matmul(X,W) + b

In [99]:
sess = tf.Session()
sess.run(tf.global_variables_initializer()) #앞서 정의한 변수들을 초기화. 기존에 학습한 값이 아니라면 필요.  ***이해 안 감***

print(x_data, '\n')
print(sess.run(W), '\n')
print(sess.run(b), '\n')
print(sess.run(expr, feed_dict={X:x_data}), '\n') #X가 플레이스 홀더. 미리 정해둔 x_data를 X의 값으로 함.  ***이해 안 감***

sess.close()

[[1, 2, 3], [4, 5, 6]] 

[[1. 1.]
 [2. 3.]
 [1. 5.]] 

[[3.]
 [7.]] 

[[11. 25.]
 [27. 56.]] 

